name: SingularityU New Zealand
favicon: null
layout_spectrum: 0.23038
typography_spectrum: 0.5035621579736471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed974c'
    - '#000000'
    - '#ede251'
    - '#5eb5e2'
  brandStrength: 0.3125
  lightness: 0.2044654635246843
  saturation: 0.36811814014799893
  rhythmicContrast: 0.9538389074150473
purpose: []
