name: SingularityU New Zealand
favicon: null
layout_spectrum: 0.8085656112525612
typography_spectrum: 0.5035621579736471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.324475011555478
  lightness: 0.2044654635246843
  saturation: 0.36811814014799893
  rhythmicContrast: 0.9538389074150473
purpose: []
